# Generated by Django 4.1.2 on 2022-10-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0002_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
