# Generated by Django 4.1.2 on 2022-10-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0003_remove_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_path',
        ),
    ]
