# Generated by Django 4.1.2 on 2022-10-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0004_remove_place_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
