# Generated by Django 4.1.2 on 2022-10-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0005_remove_place_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
