# Generated by Django 4.1.2 on 2022-10-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0006_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('coordinates_x', models.FloatField()),
                ('coordinates_y', models.FloatField()),
                ('image_path', models.FilePathField()),
            ],
        ),
    ]
