# Generated by Django 4.1.2 on 2022-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0007_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.FilePathField(verbose_name='statics/'),
        ),
    ]
