# Generated by Django 4.1.2 on 2022-10-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0012_alter_place_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates_x',
        ),
        migrations.RemoveField(
            model_name='place',
            name='coordinates_y',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_path',
        ),
    ]
