# Generated by Django 4.1.2 on 2022-10-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0013_remove_place_coordinates_x_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
