# Generated by Django 4.1.2 on 2022-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0016_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
