# Generated by Django 4.1.2 on 2022-10-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0020_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_1',
            field=models.ImageField(default=None, upload_to='siteMap/static/images/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image_2',
            field=models.ImageField(default=None, upload_to='siteMap/static/images/'),
        ),
    ]
