# Generated by Django 4.1.2 on 2022-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0021_place_image_1_place_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates_x',
            field=models.FloatField(help_text='Координаты по x'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_y',
            field=models.FloatField(help_text='Координаты по y'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(help_text='Описание  места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(help_text='Главная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_1',
            field=models.ImageField(default=0, help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_2',
            field=models.ImageField(default=0, help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(help_text='Название места'),
        ),
    ]
