# Generated by Django 4.1.2 on 2022-10-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0023_alter_place_image_1_alter_place_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_2',
        ),
    ]
