# Generated by Django 4.1.2 on 2022-10-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0024_remove_place_image_1_remove_place_image_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
