# Generated by Django 4.1.2 on 2022-10-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0026_place_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
