# Generated by Django 4.1.2 on 2022-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0028_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='0', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image1',
            field=models.ImageField(default='0', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(default='0', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(default='0', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(default='0', upload_to='siteMap/static/images/'),
        ),
    ]
