# Generated by Django 4.1.2 on 2022-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0029_alter_place_image_alter_place_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(help_text='Описание места'),
        ),
    ]
