# Generated by Django 4.1.2 on 2022-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0030_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates_x',
            field=models.FloatField(help_text='Координаты по оси x'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_y',
            field=models.FloatField(help_text='Координаты по оси y'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(help_text='Главная фотка места', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(help_text='Название нового места'),
        ),
    ]
