# Generated by Django 4.1.2 on 2022-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0031_alter_place_coordinates_x_alter_place_coordinates_y_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='image1',
            field=models.ImageField(default='0', help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(default='0', help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(default='0', help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(default='0', help_text='Дополнительная фотография', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(help_text='Название нового места', unique=True),
        ),
    ]
