# Generated by Django 4.1.2 on 2022-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0033_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='Минск', help_text='Регион местоположения'),
        ),
    ]
