# Generated by Django 4.1.2 on 2022-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0034_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.TextField(default='Минск', help_text='Регион местоположения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(help_text='Описание места'),
        ),
    ]
