# Generated by Django 4.1.2 on 2022-11-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0038_userplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(choices=[('0', 'Достопримечательности Беларуси'), ('1', 'Красивые места белорусской природы'), ('2', 'Санатории и парки семейного отдыха'), ('3', 'Места для кемпинга')], default='0', max_length=40),
        ),
    ]
