# Generated by Django 4.1.2 on 2022-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0040_place_filter_alter_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplace',
            name='filter',
            field=models.CharField(choices=[('0', 'Достопримечательности Беларуси'), ('1', 'Красивые места белорусской природы'), ('2', 'Санатории и парки семейного отдыха'), ('3', 'Места для кемпинга')], default='0', max_length=40),
        ),
    ]
