# Generated by Django 4.1.2 on 2022-11-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0042_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adress',
            field=models.CharField(help_text='Email', max_length=70),
        ),
    ]
