# Generated by Django 4.1.2 on 2022-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0043_alter_users_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='itinerary',
            field=models.CharField(default='', help_text='Маршрут', max_length=1000),
        ),
    ]
