# Generated by Django 4.1.2 on 2022-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0045_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(help_text='Название', max_length=100, unique=True),
        ),
    ]
