# Generated by Django 4.1.2 on 2022-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0046_alter_routes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='title',
            field=models.CharField(default='0', help_text='Послезвание', max_length=100),
        ),
        migrations.AlterField(
            model_name='routes',
            name='description',
            field=models.CharField(default='0', help_text='Описание', max_length=300),
        ),
        migrations.AlterField(
            model_name='routes',
            name='image',
            field=models.ImageField(default='0', help_text='Главная фотка маршрута', upload_to='siteMap/static/images/'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='points',
            field=models.CharField(default='3 5 6 9', help_text='Точки маршрута', max_length=30),
        ),
    ]
