# Generated by Django 4.1.2 on 2022-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0047_routes_title_alter_routes_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Пользователь', max_length=200)),
                ('route', models.CharField(help_text='Маршрут', max_length=100)),
                ('description', models.CharField(help_text='Описание маршрутов.', max_length=500)),
            ],
            options={
                'verbose_name': 'Пользовательский маршрут',
                'verbose_name_plural': 'Пользовательские маршруты',
                'ordering': ['user'],
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
