# Generated by Django 4.1.2 on 2022-12-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0049_usersroutess_delete_usersroutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRoutess',
        ),
    ]
