# Generated by Django 4.1.2 on 2023-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0051_usersroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplace',
            name='user',
            field=models.CharField(default='Luba_Yura', help_text='Пользователь, который добавил месте', max_length=100),
        ),
    ]
