# Generated by Django 4.1.2 on 2023-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0052_userplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='opacity',
            field=models.BooleanField(default=True, help_text='Отображение этого места (ДА или НЕТ)'),
        ),
    ]
