# Generated by Django 4.1.2 on 2023-01-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0053_place_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
    ]
