# Generated by Django 4.1.2 on 2023-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0055_place_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.CharField(default='Luba_Yura', help_text='Пользователь, который добавил месте', max_length=100),
        ),
    ]
