# Generated by Django 4.1.2 on 2023-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0057_comments_delete_userplace_alter_place_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
