# Generated by Django 4.1.2 on 2023-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMap', '0059_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(help_text='Пользователь, который добавил коммент', max_length=100),
        ),
    ]
